### ISSUE TITLE
SMTP 이메일 인증 에러

### ISSUE THREAD

**Issue by gitiss** [wafflestudio/SNUDAY-server#60]
`post /users/mail/send/`로 이메일 인증 시도 시 `500 Internel Server Error`가 발생합니다.
[localhost-1645525854885.log](https://github.com/wafflestudio/SNUDAY-server/files/8116088/localhost-1645525854885.log)

**Comment by gitiss** [comment]
이전 관련 이슈
[https://wafflestudio.slack.com/archives/C01KL18RSMT/p1633264129076700](https://wafflestudio.slack.com/archives/C01KL18RSMT/p1633264129076700)

**Comment by gitiss** [comment]
이전 관련 이슈
[https://wafflestudio.slack.com/archives/C01KL18RSMT/p1633264129076700](https://wafflestudio.slack.com/archives/C01KL18RSMT/p1633264129076700)

**Comment by IHIHHIHI** [comment]
<img width="1110" alt="스크린샷 2022-03-04 오후 2 07 10" src="https://user-images.githubusercontent.com/52493099/156702946-676d7a4d-6050-4382-816b-f149d4f30ae0.png">

**Comment by IHIHHIHI** [comment]
해결되었습니다!
