### ISSUE TITLE
채널 이미지 업로드 에러

### ISSUE THREAD

**Issue by gitiss** [wafflestudio/SNUDAY-server#61]
`POST channels/` 또는 `PATCH channels/{id}/`로
채널 이미지 업로드 시 에러가 발생합니다.

```
Exception Type: ClientError at /api/v1/channels/64/
Exception Value: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```
[localhost-1645529155218.log](https://github.com/wafflestudio/SNUDAY-server/files/8116250/localhost-1645529155218.log)

**Comment by IHIHHIHI** [comment]
S3 새로운 IAM 유저 발급받아 해결했습니다!
