### ISSUE TITLE
일정 생성 및 불러오기 에러

### ISSUE THREAD

**Issue by gitiss** [wafflestudio/SNUDAY-server#63]
`POST channels/${channelId}/events/`로 특정 기간(현재 1/25~3/8)을 벗어나는 새로운 이벤트 생성 후 

`GET user/me/events/`로 이벤트 목록을 불러오면

새로 생성한 이벤트가 목록에 없습니다.

**Comment by IHIHHIHI** [comment]
소통 오류로 확인된 이슈라 닫겠습니다.
