### ISSUE TITLE
5월 30일부터 보안 수준이 낮은 로그인 기술을 사용하는 앱에 액세스하지 못할 수 있습니다

### ISSUE THREAD

**Issue by IHIHHIHI** [wafflestudio/SNUDAY-server#74]
계정을 안전하게 보호하기 위해 Google은 사용자 이름과 비밀번호만 사용하여 Google 계정에 로그인하도록 요청하는 서드 파티 앱 또는 기기의 사용을 더 이상 지원하지 않습니다. [Google 계정으로 로그인](https://accounts.google.com/AccountChooser?Email=wafflestudio19.5.team9@gmail.com&continue=https://support.google.com/accounts/answer/112802?rfn%3D1646530984773%26anexp%3Dnret-fa) 또는 OAuth 2.0과 같이 더 안전한 다른 보안 기술을 사용하여 로그인해야 합니다. [자세히 알아보기](https://accounts.google.com/AccountChooser?Email=wafflestudio19.5.team9@gmail.com&continue=https://support.google.com/accounts/answer/6010255?rfn%3D1646530984773%26anexp%3Dnret-fa)

필요한 조치
Google 계정으로 이메일을 전송하는 데 간이 전자 우편 전송 프로토콜(SMTP)을 사용하는 앱 또는 기기는 Gmail에 액세스하기에 보안 수준이 낮습니다. 프린터나 스캐너와 같이 오래된 기기일 수 있습니다. 이러한 앱 또는 기기에서 Google 계정을 계속 사용하려면 다음 조치를 취합니다.

앱: 앱 또는 기기에서 Google 계정을 삭제한 다음 Google 계정으로 로그인을 사용하여 다시 로그인
기기: 더 안전한 로그인 기술을 사용하도록 기기 설정 변경

**Comment by HunRotation** [comment]
#94 를 통해 해결함
